package main

import (
  "fmt"
)

func main() {
  var fibonacci []int
  var even int

  fibonacci = append(fibonacci, 1, 1)
  for i := 2; fibonacci[i-1] < 4000000; i++ {
    fibonacci = append(fibonacci, (fibonacci[i-1] + fibonacci[i-2]))
    if fibonacci[i] % 2 == 0 {
      even += fibonacci[i]
    }
  }
  fmt.Println(even)
}



// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


// => 4613732
